default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

production:
  <<: *default
  <% if ENV['DATABASE_URL'] %>
  adapter: postgresql
  encoding: unicode
  <% uri = URI.parse(ENV['DATABASE_URL']) %>
  database: <%= uri.path[1..-1] %>
  username: <%= uri.user %>
  password: <%= uri.password %>
  host: <%= uri.host %>
  port: <%= uri.port %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  <% else %>
  adapter: sqlite3
  database: db/production.sqlite3
  <% end %>
